  name: unified_env
  channels:
    - conda-forge
    - defaults
    - pytorch 
  dependencies:
    - dlib
    - python=3.8
    - pip
    - altair
    - blinker
    - cachetools
    - certifi
    - charset-normalizer
    - click
    - pillow
    - requests
    - rich
    - six
    - streamlit==1.25.0
    - torch==1.10.0
    - torchvision==0.11.1
    - ultralytics==8.0.142
    - pip:
      - dlib
      - opencv-python-headless
      - matplotlib
      - numpy
      - pandas
      - pyyaml
      - scipy
      - seaborn
      - sympy
      - thop
      - torch
      - torchvision
      - tqdm
      - ultralytics