name: unified_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - altair
  - blinker
  - cachetools
  - certifi
  - charset-normalizer
  - click
  - pillow
  - requests
  - rich
  - six
  - streamlit
  - pip:
    - dlib
    - opencv-python-headless
    - matplotlib
    - numpy
    - pandas
    - pyyaml
    - scipy
    - seaborn
    - sympy
    - thop
    - torch
    - torchvision
    - tqdm
    - git+https://github.com/ultralytics/yolov8.git