  name: unified_env
  channels:
    - conda-forge
    - defaults
    - pytorch 
  dependencies:
    - python=3.8
    - pip
    - altair
    - blinker
    - cachetools
    - certifi
    - charset-normalizer
    - click
    - pillow
    - requests
    - rich
    - six
    - streamlit
    - torch
    - torchvision
    - streamlit
    - ultralytics
    - pip:
      - dlib
      - opencv-python-headless
      - matplotlib
      - numpy
      - pandas
      - pyyaml
      - scipy
      - seaborn
      - sympy
      - thop
      - torch
      - torchvision
      - tqdm
      - git+https://github.com/ultralytics/yolov8.git