name: unified_env
channels:
  - conda-forge
dependencies:
  - mamba
  - python=3.8
  - dlib
  - altair
  - blinker
  - cachetools
  - certifi
  - charset-normalizer
  - click
  - pillow
  - requests
  - rich
  - six
  - streamlit
  - torch
  - torchvision
  - numpy
  - pandas
  - pyyaml
  - scipy
  - seaborn
  - sympy
  - tqdm
  - pip
  - pip:
      - opencv-python-headless
      - matplotlib
