name: unified_env
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.8
  - dlib
  - altair
  - blinker
  - cachetools
  - certifi
  - charset-normalizer
  - click
  - pillow
  - requests
  - rich
  - six
  - streamlit=1.28.2
  - torch=1.10.0
  - torchvision=0.11.1
  - ultralytics=8.0.142
  - numpy
  - pandas
  - pyyaml
  - scipy
  - seaborn
  - sympy
  - thop
  - tqdm
  - pip
  - pip:
      - opencv-python-headless
      - matplotlib